#!/bin/sh
# SH FILE: which-shell
#
# Purpose   : Identify active shell sourcing this file.  Store result in usrhome__running_shell
# Created   : Thursday, April 11 2024.
# Author    : Pierre Rouleau <prouleau001@gmail.com>
# Time-stamp: <2024-04-11 14:44:28 EDT, updated by Pierre Rouleau>
# ----------------------------------------------------------------------------
# Module Description
# ------------------
#
# This simple script is meant to be sourced inside another sourced script.
# It identifies the running shell (zsh or Bash only) by writing the shell
# name into the usrhome__running_shell environment variable.

# ----------------------------------------------------------------------------
# Code
# ----
#
# Set usrhome__running_shell to zsh, bash or unknown

# usrhome__running_shell is not used here, it is used in script that sources
# it.
# shellcheck disable=SC2034

if test -n "$ZSH_VERSION"; then
  usrhome__running_shell=zsh
elif test -n "$BASH_VERSION"; then
  usrhome__running_shell=bash
else
  usrhome__running_shell=unknown
fi

# ----------------------------------------------------------------------------
